### ISSUE TITLE
feature request: make container startup timeout configurable

### ISSUE THREAD

**Issue by jameslamb** [NVIDIA/container-canary#61]
## Description

`canary validate` fails if the container takes more than 10 seconds to start up.

That 10 second threshold is currently hard-coded.

https://github.com/NVIDIA/container-canary/blob/a4f5c799e64cdaec661d40b909d04ca505b3e191/internal/container/docker.go#L76-L82

That timeout should be configurable.

## Benefits of this work

Would allow the use of `canary validate` with images that take longer than 10 seconds to start up, for example:

* containers that do some heavy work on startup, like starting a process and polling until it passes health checks)
* docker daemon that is running slowly, e.g. because it's performing I/O on a network filesystem or is in some other way resource-constrainted

## Acceptance Criteria

* it's possible to modify, via command-line argument(s), how long `canary validate` waits for a container to start up before timing out

## Approach

Modify this

https://github.com/NVIDIA/container-canary/blob/a4f5c799e64cdaec661d40b909d04ca505b3e191/internal/container/docker.go#L76-L82

such that that 10 second timeout can be altered via configuration.

For example, I'd like to be able to run the following:

```shell
canary validate \
   --file ./checks.yaml \
   --startup-timeout 30 \
   ${IMAGE_URI}
```

## Notes

Created this after observing this exact timeout while testing RAPIDS images over in https://github.com/rapidsai/docker/pull/670.

**Comment by jacobtomlinson** [comment]
Yup this sounds great!
